### ISSUE TITLE
Bolt circle mismatch?

### ISSUE THREAD

**Issue by jakemcivor** [mwturvey/InteractSwitch#2]
It looks like the 3 screws holes on the ButtonBase are on a 38.5 mm bolt circle, whereas the 3 matching holes in the ButtonCapHolder are on a 39.5 mm bolt circle. 

Is this intentional?

![image](https://user-images.githubusercontent.com/25379790/164325280-086533dd-7c88-451a-8d0b-a779b7289bf4.png)

![image](https://user-images.githubusercontent.com/25379790/164325344-b142726e-4dfb-4769-a6ee-09eee9267231.png)

**Comment by mwturvey** [comment]
Wow, nice find.  No, that wasn't intentional at all.  I imagine that the holder just flexes enough to make up for the difference, but it should really be 38.5mm as well.
